---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
questions = read.csv("../TAREAS_R/questions.csv", header = TRUE, sep = ",", dec = ".")
answers = read.csv("../TAREAS_R/answers.csv", header = TRUE, sep = ",", dec = ".")
tags = read.csv("../TAREAS_R/tags.csv", header = TRUE, sep = ",", dec = ".")
questions_tags = read.csv("../TAREAS_R/question_tags.csv", header = TRUE, sep = ",", dec = ".")

questions
answers
tags
questions_tags
```

1. Left-joining questions and tags

```{r}
#1.1
questions%>%
  left_join(questions_tags, by = c("id" = "question_id"))
#1.2
questions%>%
  left_join(questions_tags, by = c("id" = "question_id"))%>%
  left_join(tags, by = c("tag_id" = "id"))
#1.3
questions %>%
  left_join(questions_tags, by = c("id"="question_id")) %>%
  left_join(tags, by= c("tag_id"="id")) %>%
  replace_na(list(tag_name="only-r"))
#1.4
questions_with_tags = questions %>%
  left_join(questions_tags, by = c("id"="question_id")) %>%
  left_join(tags, by= c("tag_id"="id")) %>%
  replace_na(list(tag_name="only-r"))

questions_with_tags

```
2. Comparing scores across tags

```{r}
#2.1
questions_with_tags%>%
  group_by(tag_name)
#2.2
questions_with_tags%>%
  group_by(tag_name)%>%
  summarise(mean_score = mean(score))
#2.3
questions_with_tags%>%
  group_by(tag_name)%>%
  summarise(mean_score = mean(score))%>%
  arrange(desc(mean_score))
```


3. Finding gaps between questions and answers

```{r}
#3.1
questions %>%
  inner_join(answers, by= c("id" = "question_id"), suffix=c("_question", "_answer"))
#3.2
questions %>%
  inner_join(answers, by= c("id" = "question_id"), suffix=c("_question", "_answer"))%>%
  mutate(gap = (creation_date_answer - creation_date_question))
```

4. Joining question and answer counts

```{r}
#4.1
answer_counts = answers%>%
  count(question_id)%>%
  arrange(desc(n))

answer_counts

#4.2
questions%>%
  left_join(answer_counts, by=c("id" = "question_id"))

#4.3
questions%>%
  left_join(answer_counts, by=c("id" = "question_id"))%>%
  replace_na(list(n=0))

#4.4
questions_answer_counts = questions%>%
  left_join(answer_counts, by=c("id" = "question_id"))%>%
  replace_na(list(n=0))

questions_answer_counts

```

5. Joining questions, answers, and tags

```{r}
#5.1
questions_tags%>%
  inner_join(questions_answer_counts, by=c("question_id" = "id"))

#5.2
questions_tags%>%
  inner_join(questions_answer_counts, by=c("question_id" = "id"))%>%
  inner_join(tags, by= c("tag_id" = "id"))
```








