---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
diamonds = read.csv("../TAREAS_R/diamonds.csv", header = TRUE, sep = ",", dec = ".")
diamonds

str(diamonds)

```

1. Dispersión

```{r}
#1.1
ggplot(diamonds, aes(x = carat, y = price)) + 
  geom_point() 

#1.2 y 1.3
ggplot(diamonds, aes(x = carat, y = price, color = clarity)) + 
  geom_point() 
```

2. Histograma

```{r}
#2.1
ggplot(diamonds, aes(x=price))+ geom_histogram(bins=40)

#2.2
ggplot(diamonds, aes(x=price))+ geom_histogram(bins=40)+scale_x_log10()
```

3. Boxplots

```{r}
#3.1
ggplot(diamonds, aes(x=cut, y=price)) + geom_boxplot() + scale_y_log10()

#3.2
ggplot(diamonds, aes(x=cut, y=price, fill = cut)) + geom_boxplot() + scale_y_log10()
```

4. Faceting

```{r}

filtered_price = diamonds%>%
  filter(price > 1000, cut %in% c("Good", "Ideal", "Premium"))
  
filtered_price

#4.2
ggplot(filtered_price, aes(x=cut, y=depth)) + geom_col()

#4.3
ggplot(filtered_price, aes(x=cut, y=depth)) + geom_col() +
  facet_grid(.~clarity)

#4.4
ggplot(filtered_price, aes(x=cut, y=depth, fill=clarity)) + geom_col() +
  facet_grid(.~clarity)
```

Grouping and summarizing

```{r}
#1
median_dimenson_diamond = diamonds%>%
  group_by(cut)%>%
  summarise(mediaX = median(x), mediaY = median(y), mediaZ = median(z))
median_dimenson_diamond
```

```{r}
#2
cut_premium = diamonds%>%
  filter(cut == "Premium")%>%
  group_by(clarity)%>%
  summarise(minPrice = min(price), maxPrice = max(price))

cut_premium

```

```{r}
#3
ggplot(cut_premium, aes(x = clarity, y = maxPrice, fill = clarity)) + geom_col()
```















